version: 2.1

orbs:
  terraform: ovotech/terraform@1.6.6

jobs:
  deploy:
    executor: terraform/terraform-0_12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - terraform/version:
          path: /root/repo

      - terraform/plan:
          path: /root/repo
          backend_config: "key=global/s3/$CIRCLE_BRANCH/terraform.tfstate,bucket=$TERRAFORM_BUCKET"

      # - terraform/apply:
      #     path: /root/repo/core_infra
      #     auto_approve: true

  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: terraform init -input=false -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" -backend-config="bucket=$TERRAFORM_BUCKET" /root/project
      - run:
          name: Validate
          command: terraform validate /root/project

      - persist_to_workspace:
          root: .
          paths:
            - ./*

workflows:
  version: 2
  validate_and_deploy:
    jobs:
      - validate:
          context: DevOpsDev
          filters:
            branches:
              only:
                - /dev-.*/

      - deploy:
          context: DevOpsDev
          filters:
            branches:
              only:
                - /dev-.*/
          requires:
            - validate
