version: 2.1

orbs:
  terraform: ovotech/terraform@1.6.6

jobs:
  build:
    executor: terraform/terraform-0_12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - terraform/version:
          path: /root/repo

      - terraform/plan:
          path: /root/repo
          backend_config:
            - "key=k"
            - "bucket=b"

      # - terraform/apply:
      #     path: /root/repo/core_infra
      #     auto_approve: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: DevOpsDev
          filters:
            branches:
              only:
                - /dev-.*/
