version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Prep Artifacts
          command: |
            mkdir /tmp/artifacts;
            echo `date` > /tmp/artifacts/head;
            echo $CIRCLE_BRANCH >> /tmp/artifacts/head;
            echo $CIRCLE_BRANCH >> /tmp/artifacts/head;
            echo $CIRCLE_PROJECT_REPONAME >> /tmp/artifacts/head;
            echo $CIRCLE_PULL_REQUEST >> /tmp/artifacts/head;
      - run:
          name: Terraform Init
          command: >
            terraform init 
            -input=false 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
      - run:
          name: Terraform Plan
          command: >
            terraform plan 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
            > /tmp/artifacts/tf_plan
      - run:
          name: Terraform Apply
          command: >
            terraform apply 
            -auto-approve 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
      - run:
          name: Store Native Output
          command: >
            terraform output 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
            > /tmp/artifacts/tf_out
      - run:
          name: Store Output as JSON
          command: >
            terraform output
            -json 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
            > /tmp/artifacts/tf_out.json
      - run:
          name: Store Updated Config
          command: >
            terraform show
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
            > /tmp/artifacts/tf_show
      - run:
          name: Store Updated Config as JSON
          command: >
            terraform show
            -json
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
            > /tmp/artifacts/tf_show.json
      - store_artifacts:
          path: /tmp/artifacts

      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - ./*

  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: >
            terraform init 
            -input=false 
            -backend-config="key=global/s3/$CIRCLE_BRANCH/terraform.tfstate" 
            -backend-config="bucket=$TERRAFORM_BUCKET" 
            /root/project
      - run:
          name: Validate
          command: >
            terraform validate 
            /root/project

      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - ./*

workflows:
  version: 2
  validate_and_deploy:
    jobs:
      - validate:
          context: DevOpsDev
          filters:
            branches:
              only:
                - /dev-.*/

      - deploy:
          context: DevOpsDev
          filters:
            branches:
              only:
                - /dev-.*/
          requires:
            - validate
